---
name: Build

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  # The pipeline fails and I don't have time to debug it, if you want to help, please submit a pull request
  # PyPI:
  #   name: Build and publish Python distributions to TestPyPI
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: pdm-project/setup-pdm@main
  #       name: Setup Python and PDM
  #       with:
  #         python-version: 3.11
  #     - name: Build package
  #       run: make build-package
  #     - name: Publish distribution to Test PyPI
  #       uses: pypa/gh-action-pypi-publish@release/v1
  #       with:
  #         password: ${{ secrets.test_pypi_password }}
  #         repository_url: https://test.pypi.org/legacy/
  #         skip_existing: true
  Documentation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Number of commits to fetch. 0 indicates all history.
          # Default: 1
          fetch-depth: 0
      - uses: pdm-project/setup-pdm@main
        name: Setup Python and PDM
        with:
          python-version: 3.11
      - name: Install dependencies
        run: make install
      - name: Build the Documentation
        run: make build-docs
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
